seed_everything: 42
trainer:
  default_root_dir: "{SPECCLIP_ROOT}/outputs"
  enable_checkpointing: true
  gradient_clip_val: 1.
  max_steps: 980000
  precision: 32 
  limit_val_batches: 100
  accelerator: 'gpu'
  devices: 8 
  strategy: 'ddp'
  num_nodes: 1
  logger:
    class_path: CustomWandbLogger
    init_args:
      project: "lamost-lrs-mt"
      entity: "{WANDB_ENTITY_NAME}"
      save_dir: ${trainer.default_root_dir}
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: "step"
    - class_path: ModelCheckpoint
      init_args:
        save_last: True 
        save_top_k: 3
        monitor: "val_epoch_loss"
        mode: "min"
        filename: "{epoch}-{val_loss:.4f}"
    - class_path: CustomEarlyStopping
      init_args:
        monitor: "val_epoch_loss"
        min_delta: 1e-4
        patience: 10
        verbose: False
        mode: "min"
        check_finite: True
    - class_path: EpochLossCallback
      init_args:
        log_train_path: "{SPECCLIP_ROOT}/outputs/training_loss_lrs_mt.txt"
        log_val_path: "{SPECCLIP_ROOT}/outputs/validation_loss_lrs_mt.txt"
model:
  class_path: SpecFormerControl20_wstd
  init_args:
    input_dim: 21
    embed_dim: 768
    num_layers: 6
    num_heads: 6 
    max_len: 150 
    dropout: 0.
    mask_num_chunks: 6 
    mask_chunk_width: 10 
    slice_section_length: 20 
    slice_overlap: 10
data:
  class_path: SpectrumDataloader
  init_args:
    path: "{SPECCLIP_ROOT}/data/lamost_spectra_subsample_100.h5"
    batch_size: 64
    num_workers: 32
optimizer:
  class_path: torch.optim.adamw.AdamW
  init_args:
    lr: 1e-5
    weight_decay: 1e-1
    betas:
      - 0.9
      - 0.95
lr_scheduler:
  class_path: CosineAnnealingWithWarmupLR
  init_args:
    T_max: ${trainer.max_steps}
    T_warmup: 9760
    eta_min: ${eval:'${optimizer.init_args.lr}//100'}
